name: NGINX EC2 Deployment Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - dev
      - main

jobs:

  deploy-dev-environment:

    if: github.ref == 'refs/heads/dev'

    runs-on: [self-hosted, dev-agent]

    steps:

      - name: Step 1 - Download code from GitHub
        uses: actions/checkout@v4

      - name: Step 2 - Sync files using Rsync
        run: |
          echo "Starting file transfer to the Development Server..."
          sudo rsync -avz --delete --exclude '.git' --exclude '.github' ./ /var/www/html/

      - name: Step 3 - Restart NGINX
        run: |
          sudo systemctl restart nginx